spring:
  profiles:
    active: local
---
server:
  port: 8080
  
spring:
  profiles: local
  application:
    name: springbatch-manager
  datasource:
    url: jdbc:mariadb://localhost:3306/test # your database for Spring Batch meta-tabel 
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
  jpa:
    show-sql: true    
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
        
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%-5level] - %msg%n"
  level:
    yongs:
      temp: DEBUG


